#!/usr/bin/env python3
import sys
import argparse
import aws_kpc, aws_icc

inList = []

parser = argparse.ArgumentParser(description='Shutdown one or more running instances')
parser.add_argument("-i","--id", help="The instance id to terminate.",type=str)
parser.add_argument("-a","--all", help="Termanate all running instances.",action="store_true")
if len(sys.argv) < 2:
    parser.print_usage()
    sys.exit(1)
args = parser.parse_args()

if args.id:
    stateCode,stateString = aws_icc.aws_instance_state(args.id)

    if stateCode == 16:
        # State 16 indicates the instance is running
        print('Instance {}: {} - Terminating'.format(args.id,stateString))
        inList.append(args.id)
        aws_icc.aws_terminate_instance(inList)
        stateCode,stateString = aws_icc.aws_instance_state(args.id)
        print('Instance {}: {}'.format(args.id,stateString))
    elif stateCode == 32 or stateCode == 48:
        # State 32 indicates the instance is shutting-down
        # State 48 indicates the instance is terminated
        print('Instance {}: {}'.format(args.id,stateString))
    else:
        print('Instance {}: ({}) {} - wait until state is running (16).'.format(args.id,stateCode,stateString))
elif args.all:
    print("kill all")
    inList = aws_icc.aws_get_instances_with_state(16)
    if inList:
        aws_icc.aws_terminate_instance(inList)
    else:
        print("Nothing to terminate.")